name: Destroy Compute

on:
  workflow_dispatch:
  repository_dispatch:
    types: destroy

jobs:
  destroy-compute:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
      TF_VAR_backend_s3_bucket: ${{ secrets.TF_VAR_backend_s3_bucket }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Terraform init
        run: make compute-init

      - name: Terraform destroy
        run: make compute-destroy
